name: bdsim

on:
  push:
  pull_request:
    branches: [develop]

jobs:
  btlinux:
    name: bt linux 	
    runs-on: ubuntu-latest
    container: sboogert/${{ matrix.container }}:latest
     
    strategy:
      fail-fast: false
      matrix:
        container: [ubuntu20-g4.10.7, ubuntu20-g4.11.0, ubuntu20-g4.11.1, ubuntu20-g4.11.2,
                    ubuntu22-g4.10.7, ubuntu22-g4.11.0, ubuntu22-g4.11.1, ubuntu22-g4.11.2,
                    ubuntu24-g4.10.7, ubuntu24-g4.11.0, ubuntu24-g4.11.1, ubuntu24-g4.11.2,
                    centos8-g4.10.7, centos8-g4.11.0, centos8-g4.11.1, centos8-g4.11.2,
                    alma9-g4.10.4, alma9-g4.11.0, alma9-g4.11.1, alma9-g4.11.2]
#        container: [alma9-g4.11.2]
    steps:
      - name: Checkout bdsim
        uses: actions/checkout@v4
        id: checkout 

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - name: Working dir
        run: |
          pwd

      - name: Build bdsim
        run: |
          #
          rm -rfv /usr/local/lib/Geant4-10.7.4/Geant4PackageCache.cmake

          # ROOT 
          cd /tmp/root/bin
          . ./thisroot.sh                                                
          cd -

          # git trusted dir 
          git config --global --add safe.directory $GITHUB_WORKSPACE

          # build
          mkdir /tmp/bdsim-build
          mkdir /tmp/bdsim-install
          cd /tmp/bdsim-build
          cmake -DCMAKE_INSTALL_PREFIX=/tmp/bdsim-install $GITHUB_WORKSPACE
          make -j${{ steps.cpu-cores.outputs.count }} install

      - name: Test bdsim
        run: |
          cd /usr/local/bin/ 
          source geant4.sh

          cd /tmp/bdsim-build
          ctest -j${{ steps.cpu-cores.outputs.count }}

  btmac:
    name: bt mac
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        geant4-version: ["v10.7.4", "v11.0.4", "v11.1.3", "v11.2.2"]
        os: [macOS-13, macOS-14]
#        geant4-version: ["v10.7.4"]
#        os: [macOS-13]

    steps:
      - uses: actions/checkout@v4

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - name: Install brew dependencies on MacOS
        run: .github/bin/install-deps-macos.sh

      - name: Bison path
        shell: bash      
        run: |
          if [[ "${{ matrix.os }}" == "macOS-13" ]]; then
            echo "BISON_PATH=/usr/local/opt/bison/bin/bison" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "macOS-14" ]]; then
            echo "BISON_PATH=/opt/homebrew/opt/bison/bin/bison" >> $GITHUB_ENV
          fi


      - name: Get Geant4
        run: |
          # download geant4 build
          wget -q https://github.com/bdsim-collaboration/mac_geant4/releases/download/v0.0.21/geant4-${{ matrix.os}}-${{ matrix.geant4-version }}.tgz
          # unpack geant4
          tar zxf geant4-${{ matrix.os }}-${{ matrix.geant4-version }}.tgz -C /tmp/


      - name: Build bdsim 
        run: |
          rm -rfv /tmp/geant4-v11.0.4/lib/Geant4-11.0.4/Geant4PackageCache.cmake
          rm -rfv /tmp/geant4-v10.7.4/lib/Geant4-10.7.4/Geant4PackageCache.cmake

          # source geant4 setup
          source /tmp/geant4-${{ matrix.geant4-version }}/bin/geant4.sh
          realpath /tmp/geant4-${{ matrix.geant4-version }}/bin/geant4.sh

          # build
          mkdir /tmp/bdsim-build
          mkdir /tmp/bdsim-install
          cd /tmp/bdsim-build
          cmake -DCMAKE_INSTALL_PREFIX=/tmp/bdsim-install -DBISON_EXECUTABLE=$BISON_PATH $GITHUB_WORKSPACE
          make -j${{ steps.cpu-cores.outputs.count }} install

      - name: Test bdsim
        run: |
          cd /tmp/bdsim-build
          source /tmp/geant4-${{ matrix.geant4-version }}/bin/geant4.sh
          ctest -j${{ steps.cpu-cores.outputs.count }}